# Generated by Django 2.2 on 2020-08-23 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('description', models.CharField(max_length=100, verbose_name='Course Description')),
                ('learn_time', models.IntegerField(default=0, verbose_name='Learning Time (Minute)')),
                ('difficultly', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=2, verbose_name='Difficultly')),
                ('students', models.IntegerField(default=0, verbose_name='Students')),
                ('favorite_number', models.IntegerField(default=0, verbose_name='Favorites')),
                ('click_number', models.IntegerField(default=0, verbose_name='Number of Clicks')),
                ('category', models.CharField(default='BackEnd Development', max_length=20, verbose_name='Course Category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='Course tag')),
                ('you_should_know', models.CharField(default='', max_length=300, verbose_name='Student should know')),
                ('description_by_teach', models.CharField(default='', max_length=300, verbose_name="Teacher's words")),
                ('detail_description', models.TextField(verbose_name='Course Description')),
                ('image', models.ImageField(upload_to='courses/%Y%m', verbose_name='Course head image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Couse information',
                'verbose_name_plural': 'Couse information',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=50, verbose_name='Lesson Name')),
                ('learning_time', models.IntegerField(default=0, verbose_name='Learning time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Charter')),
            ],
            options={
                'verbose_name': 'Lesson information',
                'verbose_name_plural': 'Lesson information',
                'db_table': 'course.lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('learning_time', models.IntegerField(default=0, verbose_name='Learning Time')),
                ('url', models.CharField(max_length=200, verbose_name='URL Address')),
                ('name', models.CharField(max_length=100, verbose_name='Video Name')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Charter')),
            ],
            options={
                'verbose_name': 'Video information',
                'verbose_name_plural': 'Video information',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y%m', verbose_name='Download URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
