# Generated by Django 2.2 on 2020-08-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'Course Resources', 'verbose_name_plural': 'Course Resources'},
        ),
    ]
