# Generated by Django 2.2 on 2020-08-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200823_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficultly',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, verbose_name='Difficultly'),
        ),
    ]
