# Generated by Django 2.2 on 2020-08-23 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('comments', models.CharField(max_length=200, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Course command',
                'verbose_name_plural': 'Course command',
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
            ],
            options={
                'verbose_name': 'User courses',
                'verbose_name_plural': 'User courses',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('fav_id', models.IntegerField(verbose_name='Data id')),
                ('fav_type', models.IntegerField(choices=[(1, 'Course'), (2, 'Organization'), (3, 'Teacher')], default=1)),
            ],
            options={
                'verbose_name': 'User favorite',
                'verbose_name_plural': 'User favorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('has_read', models.BooleanField(default=False, verbose_name='Read message')),
            ],
            options={
                'verbose_name': 'User message',
                'verbose_name_plural': 'User message',
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('phone_numebr', models.CharField(max_length=10, verbose_name='Self-phone number')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'User Quesitons',
                'verbose_name_plural': 'User Quesitons',
            },
        ),
    ]
