# Generated by Django 2.2 on 2020-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200823_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(verbose_name='Comment Added Time'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(verbose_name='Message Added Time'),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='add_time',
            field=models.DateTimeField(verbose_name='Question Added Time'),
        ),
    ]
