# Generated by Django 2.2 on 2020-08-23 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=20, verbose_name='City')),
                ('description', models.CharField(max_length=100, verbose_name='Description of the city')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(max_length=50, verbose_name='Organization name')),
                ('description', models.TextField(verbose_name='Organization description')),
                ('tag', models.CharField(default='Good', max_length=10, verbose_name='Course tage')),
                ('category', models.CharField(choices=[('school', 'School'), ('personal', 'Personal'), ('university', 'University')], default='School', max_length=4, verbose_name='Type of the organization')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('image', models.ImageField(upload_to='org/%Y%m', verbose_name='Organization image')),
                ('address', models.CharField(max_length=150, verbose_name='Address of the organization')),
                ('student', models.IntegerField(default=0, verbose_name='Number of student in this course')),
                ('course_number', models.IntegerField(default=0, verbose_name='Number of courses')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Course Organization',
                'verbose_name_plural': 'Course Organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time adding this course')),
                ('name', models.CharField(default='', max_length=50, verbose_name="Tearch's name")),
                ('work_years', models.IntegerField(default=0, verbose_name='Years of experience')),
                ('work_company', models.CharField(max_length=50, verbose_name='Working company')),
                ('work_position', models.CharField(max_length=50, verbose_name='Position')),
                ('style', models.CharField(max_length=100, verbose_name='Teaching style')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('favorite_number', models.IntegerField(default=0, verbose_name='Favorites')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('image', models.ImageField(default='', max_length=60, upload_to='tearch/%Y%m', verbose_name='Image')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='Belonging organization')),
            ],
            options={
                'verbose_name': 'Tearchs in this organization',
                'verbose_name_plural': 'Tearchs in this organization',
            },
        ),
    ]
