# Generated by Django 2.2 on 2020-08-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('personal', 'Personal'), ('university', 'University')], default='School', max_length=40, verbose_name='Type of the organization'),
        ),
    ]
